plugins {
    id 'com.android.application'
}

android {
    namespace 'app.netlify.fault_summary.twa'
    compileSdk 35

    defaultConfig {
        applicationId 'app.netlify.fault_summary.twa'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
